# Generated by Django 5.0 on 2024-01-15 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_winner'),
    ]

    operations = [
        migrations.CreateModel(
            name='WatchList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_list', models.ManyToManyField(related_name='item_list', to='auctions.auctionitem')),
                ('watcher', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='watcher', to='auctions.userprofile')),
            ],
        ),
    ]
