# Generated by Django 5.0 on 2024-01-17 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_watchlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='create_auction',
            field=models.BooleanField(default=False),
        ),
    ]
