# Generated by Django 5.0 on 2024-01-17 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_alter_comment_commenter_alter_watchlist_watcher_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='create_auction',
            field=models.BooleanField(default=False),
        ),
    ]
