# Generated by Django 5.0 on 2024-01-17 14:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_alter_user_create_auction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='winner',
            name='win_item',
        ),
        migrations.AlterField(
            model_name='winner',
            name='winner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='winners', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='winner',
            name='win_item',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='win_items', to='auctions.auctionitem'),
        ),
    ]
