# Generated by Django 5.0 on 2024-01-17 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_remove_winner_win_item_alter_winner_winner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='winner',
            name='win_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='win_items', to='auctions.auctionitem'),
        ),
    ]
