# Generated by Django 5.0 on 2024-01-17 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0015_alter_winner_winner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionitem',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
